title: "Arnon on Technology"
description: "The assorted musings of a professional sysadmin. All opinions and content are my own."
author:
  name: "Arnon Erba"
  email: "arnon at arnon erba dot com"
url: "https://blog.arnonerba.com"
permalink: "/:year/:month/:title"
plugins:
  - "jekyll-feed"
  - "jekyll-paginate"
  - "jekyll-redirect-from"
  - "jekyll-relative-links"
  - "jekyll-remote-theme"
  - "jekyll-seo-tag"
  - "jekyll-sitemap"
remote_theme: "jekyll/minima"
minima:
  skin: "dark"
  show_excerpts: "true"
  social_links:
    - title: "Follow me on GitHub"
      icon: "github"
      url: "https://github.com/arnonerba"
giscus:
  repo: "arnonerba/blog"
  repo_id: "R_kgDOQwxIaw"
  category: "Comments"
  category_id: "DIC_kwDOQwxIa84C1Tn2"
  mapping: "pathname"
  strict: "1"
  reactions_enabled: "1"
  emit_metadata: "0"
  input_position: "bottom"
  theme: "dark"
  lang: "en"
  crossorigin: "anonymous"
defaults:
  - scope:
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: "assets/images"
    values:
      image: "true"
  - scope:
      path: ""
    values:
      author: "Arnon Erba"
